# Generated by Django 3.0.2 on 2020-01-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryModule', '0004_auto_20200108_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('catogories', models.ManyToManyField(to='InventoryModule.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref_number', models.CharField(max_length=15, unique=True)),
                ('item_qty', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('grand_total', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('payment_type', models.CharField(choices=[('CSH', 'Cash'), ('CHQ', 'Cheque'), ('CRD', 'Card')], max_length=3)),
                ('stock_items', models.ManyToManyField(to='InventoryModule.Stock')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PurchaseModule.Supplier')),
            ],
        ),
    ]
