# Generated by Django 3.0.2 on 2020-01-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='invoice_ref_number',
            new_name='po_number',
        ),
    ]
