# Generated by Django 3.0.2 on 2020-01-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryModule', '0004_auto_20200108_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=15, unique=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('item_qty', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('discount', models.FloatField()),
                ('grand_total', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('payment_type', models.CharField(choices=[('CSH', 'Cash'), ('CHQ', 'Cheque'), ('CRD', 'Card')], max_length=3)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='SalesModule.Customer')),
                ('stock_items', models.ManyToManyField(to='InventoryModule.Stock')),
            ],
        ),
    ]
