# Generated by Django 3.0.2 on 2020-01-06 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryModule.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(null=True)),
                ('qty_type', models.IntegerField(choices=[(1, 'KG'), (2, 'Ltr'), (3, 'Carton/Bundle')])),
                ('num_of_pieces', models.IntegerField(default=1)),
                ('qty', models.IntegerField(default=0)),
                ('min_qty', models.IntegerField(default=10, help_text='Default is 10')),
                ('purchase_price', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('selling_price', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryModule.Item')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.IntegerField(choices=[(1, 'Increased'), (2, 'Decreased')])),
                ('update_description', models.TextField()),
                ('updated_by_type', models.IntegerField(choices=[(1, 'Sales'), (2, 'Purchase'), (3, 'Sales Return'), (4, 'By User')])),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventoryModule.Stock')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
