# Generated by Django 3.0.2 on 2020-01-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryModule.Category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryModule.Item'),
        ),
    ]
