# Generated by Django 3.0.2 on 2020-01-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryModule', '0002_auto_20200107_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='InventoryModule.Item')),
                ('brand_name', models.CharField(blank=True, max_length=50)),
            ],
            bases=('InventoryModule.item',),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qty_type',
            field=models.IntegerField(choices=[(1, 'KG'), (2, 'Ltr'), (3, 'Piece'), (4, 'Carton/Bundle')]),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='InventoryModule.Item')),
                ('publisher_name', models.CharField(blank=True, max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryModule.BookType')),
            ],
            bases=('InventoryModule.item',),
        ),
    ]
