# Generated by Django 3.0.2 on 2020-01-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryModule', '0003_auto_20200107_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
